# Generated by Django 4.2.5 on 2023-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sattle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="satelliteimage",
            name="coordinates",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
