# Generated by Django 4.2.5 on 2023-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sattle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_guesses", models.IntegerField(default=0)),
                ("total_correct_guesses", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
            ],
        ),
    ]
