# Generated by Django 4.2.5 on 2023-09-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sattle", "0002_websitestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="guess",
            name="correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guess",
            name="correct_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guess",
            name="direction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guess",
            name="user_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
