# Generated by Django 4.2.5 on 2023-09-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sattle", "0002_satelliteimage_coordinates"),
    ]

    operations = [
        migrations.RemoveField(model_name="satelliteimage", name="image_url",),
        migrations.AddField(
            model_name="satelliteimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="satellite_images/"
            ),
        ),
    ]
