# Generated by Django 4.0.6 on 2023-09-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sattle', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=255, unique=True)),
                ('high_score', models.IntegerField(default=0)),
            ],
        ),
    ]
