# Generated by Django 4.0.6 on 2023-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sattle', '0006_globalhighscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
